# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Build and run tests
        run: mvn clean test
      - name: Upload Extent Report
        if: always() # upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: Extent-Report
          path: reports/*.html

      - name: Send Email with Extent Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com       # Gmail SMTP server
          server_port: 465                     # Secure SSL port
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Extent Report - ${{ github.repository }} [${{ github.run_number }}]"
          to: ravanansr7@gmail.com
          from: "GitHub Actions rajrams104@gmail.com"
          body: |
            Hello,
            The Maven test run for ${{ github.repository }} has completed.
            Please find the Extent Report attached.
          attachments: "reports/*.html"
   

